const USER_INFO_NOT_NULL = 'USER_INFO_NOT_NULL';
const USER_NAME_IS_EXISTS = 'USER_NAME_IS_EXISTS';
const USER_NAME_IS_NOT_EXISTS = 'USER_NAME_IS_NOT_EXISTS';
const PASSWORD_IS_NOT_CORRECT = 'PASSWORD_IS_NOT_CORRECT';
const TOKEN_IS_NOT_CORRECT = 'TOKEN_IS_NOT_CORRECT';
const PUBLIC_KEY_IS_NOT_CORRECT = 'PUBLIC_KEY_IS_NOT_CORRECT';
module.exports = {
  USER_INFO_NOT_NULL,
  USER_NAME_IS_EXISTS,
  USER_NAME_IS_NOT_EXISTS,
  PASSWORD_IS_NOT_CORRECT,
  TOKEN_IS_NOT_CORRECT,
  PUBLIC_KEY_IS_NOT_CORRECT,
};
