const Koa = require('koa');
const bodyParser = require('koa-bodyparser');
const app = new Koa();
const errhandle = require('./errhandle');
const useRoutes = require('../router');
app.useRoutes = useRoutes;
app.use(bodyParser());
app.useRoutes();
app.on('error', errhandle);
module.exports = app;
